### ISSUE TITLE
License Concern

### ISSUE THREAD

**Issue by tim-hub** [jaanonim/obsidian-youversion-linker#1]
Hi @jaanonim 

Thanks for your great work, 
I saw you make the plugin to support Polish book names, this is great. 👍 

> The plugins is heavily inspired by [obsidian-bible-reference](https://github.com/tim-hub/obsidian-bible-reference) (also i have "borrowed" some code from there) so check it out.
>
> [from](https://github.com/jaanonim/obsidian-youversion-linker/commit/3531f8ac479c193cd149b49ea42d727d453420b4#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)

There is one concern here about the license.

- [obsidian bible reference](https://github.com/tim-hub/obsidian-bible-reference/blob/master/LICENSE) plugin is under MIT license
- YouVersion-Linker is currently under [GPL](https://github.com/jaanonim/obsidian-youversion-linker/blob/master/LICENSE)

I don't think it is allowed to derive (MIT licensed) work to `GPL`, this is just a reminder information.

- The simplest way to make things simple is to keep it as MIT as well? I believe

> Anyway, I am not a lawyer, I am not 100% sure, just a reminder only. :) 😄

**Comment by jaanonim** [comment]
Thanks for reaching out. No problem for me I have changed the licenses to MIT.
