### ISSUE TITLE
linking doesn't seem to work past chapter

### ISSUE THREAD

**Issue by aaronr8684** [jaanonim/obsidian-youversion-linker#12]
When trying to reference a verse - e.g. `@ gal 3:1-14`

![image](https://github.com/jaanonim/obsidian-youversion-linker/assets/57102156/97516ff8-a5b4-44cd-8ba7-557b34b56184)
works up to `@ gal 3`

breaks as soon as I move past that (starting with colon).

If I generate the reference at gal 3, I can edit it manually and it works fine, it just won't auto-generate natively

YouVersion Linker
v1.1.1

System Details:
2023 Macbook Pro 16" - M2 Max
Ventura 13.4
Obsidian 1.5.3

I also got the same behavior on my personal machine with the same vault and the following details:
PC - x64
Win 10
Obsidian 1.4.16

**Comment by jaanonim** [comment]
Check for errors in developer console (to open it press `Ctrl+Shift+i`). Did you try to type it in empty note? What other plugins do you use?

**Comment by aaronr8684** [comment]
I figured out that a period `.` works for the verses (e.g. @gal 3.1-10). Is that the correct method for specifying verses? I might have missed it but was that documented somewhere?

**Comment by jaanonim** [comment]
Really I don't know if it's valid. The code supports `:` `,` and `.`. In Poland we ususually write for eg. `J 1,5` , so I thought maybe somebody will use `.`.

**Comment by aaronr8684** [comment]
So here's what it looks like on my end (using 1Tm 6:6-10 as the citation)...

Typing `@1Tm 6.6-10` (period) works fine
![image](https://github.com/jaanonim/obsidian-youversion-linker/assets/57102156/08363680-392a-4262-87b8-3f6c0ffb6e6b)


Typing `@1Tm 6,6-10` (comma) works fine
![image](https://github.com/jaanonim/obsidian-youversion-linker/assets/57102156/a8e6494e-38b3-4111-bdd0-6fd409761e09)


Typing `@1Tm 6:6-10` (colon) doesn't work starting just after the colon.
At colon:
![image](https://github.com/jaanonim/obsidian-youversion-linker/assets/57102156/9602140f-38a7-48af-9301-ddc936742693)


After colon:
![image](https://github.com/jaanonim/obsidian-youversion-linker/assets/57102156/ae2d78e9-ef4d-4b84-ba7d-40a9bf3a6c26)

**Comment by aaronr8684** [comment]
Ok, after testing and thinking about this a little more, I was able to figure it out...I have the emoji shortcode plugin (for fancy checkmarks, etc.) that was catching the colon.
![image](https://github.com/jaanonim/obsidian-youversion-linker/assets/57102156/85426ce0-3052-4074-9ef1-55b670de482e)


When disabled, the full citation works...
![image](https://github.com/jaanonim/obsidian-youversion-linker/assets/57102156/d7438a7b-ef2d-40f5-9bfc-062fd6701d69)

Not sure if you want to mention this in your documentation, but I'll close this issue since it's not directly related to your code. Thanks for the help!
