### ISSUE TITLE
Insert content of verse into note and multiple languages support

### ISSUE THREAD

**Issue by junwhuan** [jaanonim/obsidian-youversion-linker#15]
Hi Jaanonim, I have two requests:
1. Would it be possible to display the verse content? Currently we only put the book:chapter:verses in note, when user hover, they can see the content. Would it be possible like the plugin [obsidian-bible-reference](https://github.com/tim-hub/obsidian-bible-reference) to display the content in note?
2. Can this plugin support multiple languages at the same time? I generally need two languages. I feel this is more convenience for people whose mother languages is not English.

**Comment by jaanonim** [comment]
1. You are a second person that ask about it. It would be possible, but I don't think it's needed because [obsidian-bible-reference](https://github.com/tim-hub/obsidian-bible-reference) does great job with it. If more people will be interested, I may implement it.

**Comment by jaanonim** [comment]
2. What do you mean by that? You can chose in settings to what translation you link and all names of books in all [suported languages](Languages.md) work at the same time.

**Comment by junwhuan** [comment]
> 2. What do you mean by that? You can chose in settings to what translation you link and all names of books in all suported languages work at the same time.

I want to refer both languages at the same place. In current plugin (or other plugins), we can only choose one language.

**Comment by jaanonim** [comment]
How would that work? Multiple translation in one link or two links?

**Comment by junwhuan** [comment]
Either way is fine. So let's say: John 1:1 and 约1:1 (This is Chinese). 
Or if we just put john 1:1 and then it will popup two language verses. 

Currently I may try to rename your plugin and have additional clone plugin in local obsidian. And setup bible different language in each plugin. I may try it later today. 

But ideally it would be nice if you could have that function supported. Which means configurable in the plugin to support multiple languages.

**Comment by jaanonim** [comment]
Okej that's doable.

**Comment by junwhuan** [comment]
I currently installed a cloned plugin, however, the trigger can be different, but the version is loaded as the first plugin. 
(how to install plugin twice https://forum.obsidian.md/t/how-to-install-a-duplicate-plugin-i-e-the-same-plugin-twice-under-a-different-name/42863/2)

Do you have any comment that I need to change the main.js?

**Comment by jaanonim** [comment]
2 issue fixed in #16

**Comment by jaanonim** [comment]
1 issue fixed in #28

**Comment by spcano01** [comment]
Awesome, thank you!  Can't wait to try it out and compress down to just this one.  Really liked all of them (linker, reference, and this one), but they all did it differently.  Tried to use two at same time, but couldn't figure it out, so fell back to reference.  

But if when it links to Bible app vs random site, this will be killer app for me personally.

**Comment by corex** [comment]
> 1. You are a second person that ask about it. It would be possible, but I don't think it's needed because [obsidian-bible-reference](https://github.com/tim-hub/obsidian-bible-reference) does great job with it. If more people will be interested, I may implement it.

I would love this feature. I come from Denmark and so far I have only found Danish language support in this plugin.

**Comment by jaanonim** [comment]
@corex 
As i mentioned feature for embedding versus content into note was added in #28. You can do it by typing eg. '>John 1:1'.

**Comment by corex** [comment]
Oh, i misunderstood that comment. Thanks for clarifying.
