### ISSUE TITLE
A bit of both?  Reference + Youversion?  Either way, great plugin - thank you

### ISSUE THREAD

**Issue by spcano01** [jaanonim/obsidian-youversion-linker#28]
**meant to add enhancement tag, apologies.

Awesome plugin!  Only thing keeping me from using this exclusively/fully is the ability to just bring in the actual verse vs simply linking (ala Bible Reference).  If I could see the verse in my notes but when I want to dig in, go into my YouVersion, this would be amazing!  

I know it works via hover, but I take my notes on my cell, which doesn't seem to use hover.

**Comment by jaanonim** [comment]
As you are another person that asks for that i will start working on this.

**Comment by spcano01** [comment]
It's perfect, thank you so much!
