### ISSUE TITLE
Which language codes should be used?

### ISSUE THREAD

**Issue by cmeeren** [jaanonim/obsidian-youversion-linker#5]
I am considering adding book translations for Norwegian, but I'm wondering which language codes should be used. There's Norwegian Bokmål and Norwegian Nynorsk which differ slightly, so possible language codes I have seen elsewhere include `no`, `nob`, `nno`, and `nor`. I'm not sure which to use here (or if it matters).

**Comment by jaanonim** [comment]
I'm not Norwegian so I don't those codes. You can add multiple codes for the same book so you can add both if you want.

**Comment by jaanonim** [comment]
It's only important that 2 books won't have the came code :-)

**Comment by cmeeren** [comment]
> I'm not Norwegian so I don't those codes.

I was thinking that the codes had to correspond to some ISO standard, but if the actual code is not used for anything other than ensuring unique filenames, then that's not an issue. 🙂

> It's only important that 2 books won't have the came code :-)

Got it!

**Comment by cmeeren** [comment]
By the way, for books with numbers like 1 samuel, do I need to add both "1sam" and "1 sam" (with and without space)? I guess not, because I can't see that in the English files and it works both with and without them, but I wanted to ask to make sure.

**Comment by jaanonim** [comment]
If you add "1sam", "1 sam" will work  too. It's ignoring whitespace.

**Comment by cmeeren** [comment]
Great, thanks!
